### ISSUE TITLE
Preprocessing is not saving the SPRING files

### ISSUE THREAD

**Issue by abzhanguab** [AllonKleinLab/SPRING#2]
Hello, I am still pretty new to programming; So, please bear with me. I am receiving the following error when running the preprocessing scripts provided. The code stops during the "Saving Spring Plot" sequence. The frog_python folder doesn't seem to be created and the resulting files aren't saving. I was wondering if you know a solution to this issue. The following error is shown:

File "C:\Users\abzhang\Documents\GitHub\SPRING\preprocessing.py", line 43, in <module>
    save_spring_dir(E,D,5,gene_list,'datasets/frog_python', cell_groupings=cell_groupings, custom_colors=custom_colors, coarse_grain_X=1)
  File "C:\Users\abzhang\Documents\GitHub\SPRING\preprocessing_python.py", line 207, in save_spring_dir
    write_color_tracks(all_gene_colors, fname)
  File "C:\Users\abzhang\Documents\GitHub\SPRING\preprocessing_python.py", line 309, in write_color_tracks
    open(fname,'w').write('\n'.join(out))
IOError: [Errno 2] No such file or directory: 'datasets/frog_python//gene_colors/color_data_all_genes-0.csv'

**Comment by swolock** [comment]
I suspect this is a Windows compatibility issue with a couple lines of code. It should be fixed in the latest commit.

**Comment by abzhanguab** [comment]
Thank you

**Comment by abzhanguab** [comment]
Hello, I believe the update fixed the compatibility issue, but now, I am getting an attribute error. Was I supposed to define the project directory somewhere? Sorry still very new to this.

Traceback (most recent call last):
  File "C:\Users\abzhang\Documents\GitHub\SPRING\preprocessing.py", line 43, in <module>
    save_spring_dir(E,D,5,gene_list,'datasets/frog_python', cell_groupings=cell_groupings, custom_colors=custom_colors, coarse_grain_X=1)
  File "C:\Users\abzhang\Documents\GitHub\SPRING\preprocessing_python.py", line 181, in save_spring_dir
    os.system.makedirs(project_directory)
AttributeError: 'builtin_function_or_method' object has no attribute 'makedirs'

**Comment by swolock** [comment]
Sorry, I introduced a bug when I fixed the compatibility issue. Please try again.

**Comment by abzhanguab** [comment]
It works fine now! Thank you!
