### ISSUE TITLE
Problem with SPRING visualization

### ISSUE THREAD

**Issue by camilliano** [AllonKleinLab/SPRING#4]
Hi everyone!

I have some issues when I want to visualize my data using SPRING. 

I process my own data following the tutorial (in python).
At the end I save my directory:
**save_spring_dir**(E,D,5,gene_names,'/site/rp/home/I0355555/Downloads/SPRING-master/datasets/MY_DATA' )
and in **SPRING-master/datasets** there is: _categorical_coloring_data.json, color_data_gene_sets.csv, color_stats.json, gene_colors folder and graph_data.json_.

But when I run this:  http://localhost:8000/springViewer.html?PATH_TO_MY_PROJECT_DIRECTORY
there nothing on the screen...

I don't understand how to manage this issue... 
thanks all for your help!

**Comment by calebweinreb** [comment]
Hello,

The "PATH_TO_MY_PROJECT_DIRECTORY
<http://localhost:8000/springViewer.html?PATH_TO_MY_PROJECT_DIRECTORY>"
part of the URL is meant to be replaced by the path to your project
directory. Does it work when you appropriately modify the URL. Also did you
start a local server as described in the readme?

Thanks,
Caleb

**Comment by calebweinreb** [comment]
By the way, for a quick first look at your data you might also try going
through our more user-friendly online upload site
https://kleintools.hms.harvard.edu/tools/spring.html

**Comment by camilliano** [comment]
yep, I did replace the path to my project (and the local host) and I did start a local server.

I have this error:
```
27.0.0.1 - - [25/Apr/2018 14:23:11] code 404, message File not found
127.0.0.1 - - [25/Apr/2018 14:23:11] "HEAD /SC08_CTRL_3H/gene_colors/color_data_all_genes-1.csv HTTP/1.1" 404 - 

127.0.0.1 - - [25/Apr/2018 14:23:11] code 404, message File not found 
```
...........
although I don't understand why because I have all the files in the datasets folder...

**Comment by calebweinreb** [comment]
Can you share the SPRING directory via dropbox or google drive with my
email address? (calebsw@gmail.com)

**Comment by camilliano** [comment]
actually, I cannot share any informations...
everything is blocked on my computer (security)

**Comment by calebweinreb** [comment]
OK. My best advice is to debug by systematically comparing to the example
dataset that is provided in the github (I think it's called "centroids")
and otherwise go through the online upload portal.

The file that appears to be missing from your command line copy/paste is
something in the "gene_colors" directory. Are there 50 csv files in the
"gene_colors" directory inside your SPRING project folder?

**Comment by camilliano** [comment]
yep there are all here (from 0 to 49)

**Comment by swolock** [comment]
Just to make sure we understand the issue, I want to clarify a couple things.

First, you have saved your SPRING data in a folder called /site/rp/home/I0355555/Downloads/SPRING-master/datasets/MY_DATA

So categorical_coloring_data.json, color_data_gene_sets.csv, etc. should be in SPRING-master/datasets/MY_DATA/, not SPRING-master/datasets/.

Second, are you starting the local host in SPRING-master?
`cd /site/rp/home/I0355555/Downloads/SPRING-master/` 
`python -m SimpleHTTPServer 8000`  

And then navigating to http://localhost:8000/springViewer.html?datasets/MY_DATA ?

**Comment by camilliano** [comment]
OMG!
I know I what is the problem (I am ashamed).
So:
categorical_coloring_data.json, color_data_gene_sets.csv, etc. are indeed in **SPRING-master/datasets/MY_DATA/** OK
and yes, I start `python -m SimpleHTTPServer 8000` in SPRING-master OK
this is what I was doing : **http://localhost:8000/springViewer.html?/MY_DATA** not OK
and then : **http://localhost:8000/springViewer.html?datasets/MY_DATA** 

So sorry, 
thank you Caleb for your time!

**Comment by calebweinreb** [comment]
Glad we got to the bottom of it!!

**Comment by calebweinreb** [comment]
By the way, if you have >4000 cells I would seriously recommend switching
to the newer version of SPRING (https://github.com/AllonKleinLab/SPRING_dev)
